name: ci

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04
          cpu: ppu
        - os: ubuntu-22.04
          cpu: spu
    defaults:
      run:
        shell: bash

    outputs:
      sha8: ${{ steps.slug.outputs.sha8 }}
      date: ${{ steps.date.outputs.date }}

    steps:
    - uses: actions/checkout@v4

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Get current arch
      id: arch
      run: echo "::set-output name=arch::$(uname -m)"

    - name: Install Ubuntu requirements
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt update
    
    - name: Install macOS requirements
      if: startsWith(matrix.os, 'macos')
      # act -P macos-latest=-self-hosted --container-architecture linux/amd64
      run: |
        brew update
        brew install autoconf automake openssl libelf ncurses zlib gmp wget pkg-config gnu-sed texinfo
        echo "alias sed='gsed'" >> ~/.bashrc

        # check current version
        python --version
        #python-config --libs
        
        # install pyenv
        brew install pyenv
        # Initialize pyenv in the current shell
        eval "$(pyenv init --path)"

        # Install Python 3.11 using pyenv
        pyenv install 3.11.0
        # Set Python 3.11 as the global version
        pyenv global 3.11.0
        pip install python-config
        echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
        echo 'pyenv global 3.11.0' >> ~/.bashrc
        echo 'echo bashrc loaded' >> ~/.bashrc

    - name: Runs all the stages in the shell
      run: |
        . ~/.bashrc
        if [ ${{ matrix.cpu }} = "ppu" ]; then
            rm -rf -v scripts/*spu*
        else
            rm -rf -v scripts/*ppu*
        fi
        mkdir -p $PWD/ps3dev
        export PS3DEV=$PWD/ps3dev
        export PSL1GHT=$PS3DEV
        export PATH=$PATH:$PS3DEV/bin
        export PATH=$PATH:$PS3DEV/ppu/bin
        export PATH=$PATH:$PS3DEV/spu/bin
        export PATH=$PATH:$PS3DEV/portlibs/ppu/bin
        export PKG_CONFIG_PATH=$PS3DEV/portlibs/ppu/lib/pkgconfig
        bash arm64.sh
